version: 0.2

phases:
  install:
    commands:
echo Installing NGINX
sudo apt-get update
sudo apt-get install nginx -y
  build:
    commands:
echo Build started on `date`
cp index.html /var/www/html/
  post_build:
    commands:
echo Configuring NGINX
  pre_build:
    commands:
echo Nothing to do in the pre_build phase...

artifacts:
  files:
"**/*"
